services:

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    restart: always
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: $REACT_APP_API_URL
        REACT_APP_EMAILJS_SERVICE_ID: ${REACT_APP_EMAILJS_SERVICE_ID}
        REACT_APP_EMAILJS_TEMPLATE_ID: ${REACT_APP_EMAILJS_TEMPLATE_ID}
        REACT_APP_EMAILJS_PUBLIC_KEY: ${REACT_APP_EMAILJS_PUBLIC_KEY}
    container_name: frontend
    ports:
      - "3000:80"
    restart: always