services:

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    restart: always

  
  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: https://backend-202366413188.europe-central2.run.app
    container_name: frontend
    ports:
      - "3000:80"
    restart: always