services:

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    restart: always

  
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_URL: http://backend:8000
    depends_on:
      - backend
    restart: always